const S={rows:12,cols:12,cells:[],selected:null,mode:'creator'};const $=s=>document.querySelector(s);const arrows={R:'→',D:'↓',L:'←',U:'↑'};
function fresh(){S.cells=Array.from({length:S.rows*S.cols},()=>({type:'empty',letter:'',clues:[],owners:[]}));S.selected=null;render();}
function idx(r,c){return r*S.cols+c} function rc(i){return [Math.floor(i/S.cols),i%S.cols]}
function render(){const g=$('#grid');g.className='grid';g.style.gridTemplateColumns=`repeat(${S.cols},54px)`;g.innerHTML='';S.cells.forEach((x,i)=>{const d=document.createElement('div');d.className=`cell ${x.type}${S.selected===i?' selected':''}${x.conflict?' conflict':''}`;d.dataset.i=i;if(x.type==='letter')d.textContent=x.letter||'';if(x.type==='clue'){d.classList.add(['','one','two','three'][Math.min(3,x.clues.length)]||'one');x.clues.forEach(q=>{const p=document.createElement('div');p.className='cluePart';p.innerHTML=`${esc(q.text)} <span class="arrow">${arrows[q.dir]||''}</span>`;d.appendChild(p)})}d.onclick=()=>select(i);g.appendChild(d)});$('#paperTitle').textContent=$('#title').value||'Integramă';}
function esc(s){return (s||'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function select(i){S.selected=i;$('#emptyState').hidden=true;$('#editor').hidden=false;const x=S.cells[i];$('#cellType').value=x.type==='empty'?'empty':x.type;$('#letter').value=x.letter||'';$('#clueCount').value=Math.max(1,x.clues.length||1);buildClues(x.clues);toggleFields();render()}
function buildClues(vals=[]){const n=+$('#clueCount').value;$('#clues').innerHTML='';for(let i=0;i<n;i++){const v=vals[i]||{text:'',dir:'R'};$('#clues').insertAdjacentHTML('beforeend',`<div class="row"><label>Indiciu ${i+1}<input class="ct" value="${esc(v.text)}"></label><label>Direcție<select class="cd">${Object.entries(arrows).map(([k,a])=>`<option value="${k}" ${v.dir===k?'selected':''}>${a}</option>`).join('')}</select></label></div>`)}}
function toggleFields(){const t=$('#cellType').value;$('#letterFields').hidden=t!=='letter';$('#clueFields').hidden=t!=='clue'}
$('#cellType').onchange=toggleFields;$('#clueCount').onchange=()=>buildClues();$('#apply').onclick=()=>{if(S.selected==null)return;const t=$('#cellType').value,x=S.cells[S.selected];x.type=t;x.conflict=false;if(t==='letter'){x.letter=$('#letter').value.toUpperCase();x.clues=[]}else if(t==='clue'){x.letter='';x.owners=[];x.clues=[...document.querySelectorAll('.ct')].map((e,i)=>({text:e.value,dir:document.querySelectorAll('.cd')[i].value}))}else{x.letter='';x.clues=[];x.owners=[]}render()};
function pathFrom(start,word,dir){const [r,c]=rc(start),v={R:[0,1],L:[0,-1],D:[1,0],U:[-1,0]}[dir],out=[];for(let k=1;k<=word.length;k++){let rr=r+v[0]*k,cc=c+v[1]*k;if(rr<0||cc<0||rr>=S.rows||cc>=S.cols)return null;out.push(idx(rr,cc))}return out}
$('#place').onclick=()=>{clearMsg();if(S.selected==null)return msg('Selectează mai întâi celula de indiciu.');const word=$('#answer').value.trim().toUpperCase().replace(/\s+/g,''),def=$('#definition').value.trim(),dir=$('#direction').value;if(!word||!def)return msg('Completează răspunsul și definiția.');let clue=S.cells[S.selected];if(clue.type!=='clue'){clue.type='clue';clue.letter='';clue.owners=[];clue.clues=[]}if(clue.clues.length>=3)return msg('Această celulă are deja 3 indicii.');const p=pathFrom(S.selected,word,dir);if(!p)return msg('Nu este suficient spațiu în grilă pentru acest răspuns.');for(let j=0;j<p.length;j++){const x=S.cells[p[j]];if(x.type==='clue'||x.type==='block')return msg('Răspunsul ar trece printr-o celulă de indiciu/blocată.');if(x.type==='letter'&&x.letter&&x.letter!==word[j])return msg(`Conflict de litere: grila are „${x.letter}”, iar răspunsul cere „${word[j]}”.`)}clue.clues.push({text:def,dir,answer:word});p.forEach((pi,j)=>{let x=S.cells[pi];x.type='letter';x.letter=word[j];x.owners.push({clue:S.selected,answer:word,dir})});render();msg('Răspuns adăugat fără conflicte.',true)};
function validate(){S.cells.forEach(x=>x.conflict=false);let issues=[];S.cells.forEach((x,i)=>{if(x.type==='letter'&&!x.letter)issues.push(`Celula ${i+1}: literă lipsă.`);if(x.type==='letter'&&x.owners.length===0)issues.push(`Celula ${i+1}: literă fără răspuns asociat.`);if(x.type==='clue'&&x.clues.length===0)issues.push(`Celula ${i+1}: indiciu gol.`)});render();$('#summary').innerHTML=issues.length?`<b>Verificare:</b> ${issues.length} problemă(e).<br>${issues.slice(0,8).map(esc).join('<br>')}`:'<b>Verificare:</b> grila nu are probleme structurale evidente.';return issues}
$('#check').onclick=validate;$('#resize').onclick=()=>{S.rows=Math.max(5,Math.min(30,+$('#rows').value||12));S.cols=Math.max(5,Math.min(30,+$('#cols').value||12));fresh()};$('#title').oninput=render;$('#print').onclick=()=>{validate();window.print()};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));S.mode=b.dataset.mode;document.body.classList.toggle('reader',S.mode==='reader');render()});function msg(t,ok=false){$('#message').className=ok?'ok':'warn';$('#message').textContent=t}function clearMsg(){msg('')};fresh();
